#!/usr/bin/env python3
import xml.dom.minidom
import uuid
import posixpath

name_target='maas-node-01'
uuid_target=str(uuid.uuid1())

dom = xml.dom.minidom.parse('data/maas-node.xml')

domain_ele = dom.getElementsByTagName('domain')[0]
if isinstance(domain_ele, xml.dom.minidom.Element):
    domain_ele.setAttribute('id', '10')

name_ele = dom.getElementsByTagName('name')[0]
name_node = name_ele.childNodes[0]
name_node.data = name_target

uuid_ele = dom.getElementsByTagName('uuid')[0]
uuid_node = uuid_ele.childNodes[0]
uuid_node.data = uuid_target

disk_ele = dom.getElementsByTagName('disk')[0]
source_ele = disk_ele.childNodes[3]
if isinstance(source_ele, xml.dom.minidom.Element):
    qcow2_file = source_ele.getAttribute('file')
qcow2_dir = posixpath.dirname(qcow2_file)
qcow2_file = posixpath.join(qcow2_dir, name_target + '.qcow2')
source_ele.setAttribute('file', qcow2_file)

sec_eles = dom.getElementsByTagName('seclabel')
for ele in sec_eles:
    nodes = ele.childNodes
    for node in nodes:
        if isinstance(node, xml.dom.minidom.Element):
            sub_node = node.childNodes[0]
            sub_node.data = "libvirt" + uuid_target

output_xml = open(name_target + '.xml', 'w')
dom.writexml(output_xml)
output_xml.close()
